import{S as w,N as d,a as b}from"./assets/vendor-RBnklswU.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&o(a)}).observe(document,{childList:!0,subtree:!0});function l(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=l(e);fetch(e.href,t)}})();let u;function m(i){const n=document.querySelector(".gallery"),l=i.map(o=>`
    <a href="${o.largeImageURL}" class="gallery-item">
      <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy"/>
      <div class="info">
        <p>Likes: ${o.likes}</p>
        <p>Views: ${o.views}</p>
        <p>Comments: ${o.comments}</p>
        <p>Downloads: ${o.downloads}</p>
      </div>
    </a>
  `).join("");n.insertAdjacentHTML("beforeend",l),u?u.refresh():u=new w(".gallery a")}function P(){document.querySelector(".gallery").innerHTML=""}function p(){document.getElementById("loader").classList.remove("hidden")}function h(){document.getElementById("loader").classList.add("hidden")}document.addEventListener("DOMContentLoaded",()=>{const i="46234405-5fabb3e7cd0fd4a5073c0abd3",n="https://pixabay.com/api/";let o="",e=1,t=0;const a=document.getElementById("search-form"),c=document.getElementById("load-more-btn"),g=document.querySelector(".gallery");async function f(r,s){const L=`${n}?key=${i}&q=${encodeURIComponent(r)}&image_type=photo&orientation=horizontal&safesearch=true&page=${s}&per_page=15`;try{return(await b.get(L)).data}catch(y){throw d.Notify.failure("Oops, something went wrong. Try again later."),new Error(y)}}a.addEventListener("submit",async r=>{r.preventDefault(),P(),o=r.target.query.value.trim(),e=1,c.style.display="none",p();try{const s=await f(o,e);if(t=s.totalHits,t===0){d.Notify.failure("No images found. Try another query.");return}m(s.hits),d.Notify.success(`Hooray! We found ${t} images.`),t>15&&(c.style.display="block")}catch(s){console.error(s)}finally{h()}}),c.addEventListener("click",async()=>{e+=1,p();try{const r=await f(o,e);m(r.hits),e*15>=t&&(c.style.display="none",d.Notify.info("We're sorry, but you've reached the end of search results.")),E()}catch(r){console.error(r)}finally{h()}});function E(){const{height:r}=g.firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}});
//# sourceMappingURL=index.js.map
